# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rolling_pair_stats_cpp <- function(x, y, window, min_obs = 10L) {
    .Call(`_EnergyAnalytics_rolling_pair_stats_cpp`, x, y, window, min_obs)
}

black76_greeks_vectorised <- function(F, K, r, T, sigma, is_call) {
    .Call(`_EnergyAnalytics_black76_greeks_vectorised`, F, K, r, T, sigma, is_call)
}

